version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/jobfinderapi/
    overwrite: true

file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
      timeout: 180
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_django.sh
      timeout: 180