version: 0.2

phases:
  install:
    commands:
      - sudo yum update -y
      - sudo amazon-linux-extras enable postgresql14
      - sudo yum install -y postgresql14 postgresql14-devel
      - pip install --upgrade psycopg2-binary
      - sudo pip3 install virtualenv
      # Create a virtual environment in your project directory
      - python3 -m venv venv  # Create virtual environment in 'venv' directory

      # Activate the virtual environment
      - source venv/bin/activate  # Activate virtual environment

      # Install dependencies from requirements.txt
      - pip install -r requirements.txt


  pre_build:
    commands:
      - export SECRET=$(aws secretsmanager get-secret-value --secret-id django-project_env_variable --query SecretString --output text)
      - export SECRET_KEY=$(echo $SECRET | jq -r .SECRET_KEY)
      - export DB_NAME=$(echo $SECRET | jq -r .DB_NAME)
      - export DB_USER=$(echo $SECRET | jq -r .DB_USER)
      - export DB_PASSWORD=$(echo $SECRET | jq -r .DB_PASSWORD)
      - export DB_HOST=$(echo $SECRET | jq -r .DB_HOST)
      - export AWS_ACCESS_KEY_ID=$(echo $SECRET | jq -r .AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRET | jq -r .AWS_SECRET_ACCESS_KEY)
      - export AWS_STORAGE_BUCKET_NAME=$(echo $SECRET | jq -r .AWS_STORAGE_BUCKET_NAME)
      - export DJANGO_SETTINGS_MODULE=$(echo $SECRET | jq -r .DJANGO_SETTINGS_MODULE)
      - echo "Environment variables exported successfully."

  build:
    commands:
      - echo "Running migrations..."
      - python manage.py makemigrations
      - python manage.py migrate --noinput
      - python maanage.py pytest
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
