version: 0.2

phases:
  install:
    commands:
      - echo "Installing packages from requirements.txt..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - source /etc/apache2/envvars
      - echo "Environment variables exported successfully."

  build:
    commands:
      - echo "Running migrations..."
      - python manage.py makemigrations
      - python manage.py migrate --noinput
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'