version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: jobfinderapi.settings
    SECRET_KEY: KDFGJDKLGFJKLç_ç8989898989JKHLKHJKHJKHJK
    DATABASE_DEFAULT_URL: postgres://postgres:postgresd@localhost:5432/jobfinderapi
    DATABASE_STREAMDATA_URL: postgres://postgres:postgresd@localhost:5432/jobfinderapi
    STREAM_INCOMING_PRIVATE_KEY: stremkeyprivate
    STREAM_INCOMING_PUBLIC_KEY: stremkeypublic
    OPBEAT_ENABLED: False

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'