version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.11  # Use the version you're using
      commands:
        # Install Apache and mod_wsgi for Django
        - sudo pip3 install -r requirements.txt

  pre_build:
    commands:
      - export SECRET=$(aws secretsmanager get-secret-value --secret-id django-project_env_variable --query SecretString --output json)
      - export SECRET_KEY=$(echo $SECRET | jq -r .SECRET_KEY)
      - export DB_NAME=$(echo $SECRET | jq -r .DB_NAME)
      - export DB_USER=$(echo $SECRET | jq -r .DB_USER)
      - export DB_PASSWORD=$(echo $SECRET | jq -r .DB_PASSWORD)
      - export DB_HOST=$(echo $SECRET | jq -r .DB_HOST)
      - export AWS_ACCESS_KEY_ID=$(echo $SECRET | jq -r .AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRET | jq -r .AWS_SECRET_ACCESS_KEY)
      - export AWS_STORAGE_BUCKET_NAME=$(echo $SECRET | jq -r .AWS_STORAGE_BUCKET_NAME)
      - export DJANGO_SETTINGS_MODULE=$(echo $SECRET | jq -r .DJANGO_SETTINGS_MODULE)
      - echo "Environment variables exported successfully."

  test:
    commands:
      # Run Django tests here
      - echo "Running tests..."
      - source /venv/bin/activate  # Activate virtualenv if used
      - python manage.py pytest

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: yes