# Generated by Django 5.1.1 on 2025-02-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='contract',
        ),
        migrations.AddField(
            model_name='offer',
            name='contract',
            field=models.ManyToManyField(to='offers.contracttype'),
        ),
    ]
