# Generated by Django 5.1.1 on 2025-02-10 14:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_contracttype_remove_offer_contract_offer_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='offers_offe_search__f66b18_gin'),
        ),
    ]
